apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - name: sample-app
        image: asia-south1-docker.pkg.dev/ccd-poc-project/sample-app/sample-app:44ec33df9b18438c3570fe412d2be133f5a0babf
        ports:
        - containerPort: 80
