apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - name: sample-app
        image: asia-south1-docker.pkg.dev/ccd-poc-project/sample-app/sample-app:5a8c347edf4a5a12c7667635ee83677ea55b6cce
        ports:
        - containerPort: 80
