apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - name: sample-app
        image: asia-south1-docker.pkg.dev/ccd-poc-project/sample-app/sample-app:2dcf2ed349248cfc6a29028ae4db6ee1fec22e1e
        ports:
        - containerPort: 80
